### ISSUE TITLE
TypeNotFound: Type not found: '(schema, http://www.w3.org/2001/XMLSchema, )

### ISSUE THREAD

**Issue by shaunc869** [thurloat/appengine-suds#1]
Hi! 

When I run:

```
url='https://apitest.integrapay.com.au/PayLinkService.svc?singleWsdl'

        imp = Import('http://schemas.xmlsoap.org/soap/encoding/', location='http://schemas.xmlsoap.org/soap/encoding/')
        imp.filter.add('http://ws.client.com/Members.asmx')
        client = Client(url, username='1479', password='4e_EM9b+7/N', plugins=[ImportDoctor(imp)])
        log.info("Got client:" + unicode(client))
```

I get:

`TypeNotFound: Type not found: '(schema, http://www.w3.org/2001/XMLSchema, )'`

Any idea why this might be happening, I have been digging through code for days trying to fix it, but I just wanted to see if you had any clue. Thanks for the help!

**Comment by thurloat** [comment]
Hi Shaun,

No idea what would be causing that issue for you. 

If you check out commit 3ffd04696110e130b32f9bceedc595c2ace6bf23, it's essentially the only thing that needed to be done to get the project working on AppEngine -- and this was forked over 3 years ago. Perhaps there have been updates to the project since then, and you can re-apply the same type of fix to the main project to get it working for you.
